version: '3.8'

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    depends_on:
      - backend
      - frontend
    networks:
      - app-network
    volumes:
      - ./back:/var/www
      - ./nginx.conf:/etc/nginx/nginx.conf

  frontend:
    build:
      context: ./front
      dockerfile: _docker/frontend/Dockerfile
    container_name: frontend
    networks:
      - app-network
    depends_on:
      - db
    ports:
      - "3000:3000"

  backend:
    build:
      context: ./back
      dockerfile: _docker/backend/Dockerfile
    container_name: backend
    networks:
      - app-network
    depends_on:
      - db
    volumes:
      - ./back:/var/www

  db:
    image: mysql:8.0
    container_name: db
    env_file:
      - env/mysql.env
    ports:
      - "3306:3306"
    networks:
      - app-network

networks:
  app-network: